package com.example.accountingassistant.enums;

public enum State {

    FREE,

    FAQ_WAIT_QUESTION,

    CALC_WAIT_FORM, CALC_WAIT_MODE, CALC_WAIT_EMPLOYEE, CALC_WAIT_MONEY_TURNOVER, CALC_WAIT_OPERATION,
    CALC_WAIT_NDS_AGENT, CALC_WAIT_NDFL_AGENT, CALC_WAIT_AGENCY_CONTRACT, CALC_WAIT_VED, CALC_WAIT_DETACHED,
    CALC_WAIT_DOCUMENT_MATCHING,

    CANCEL
}
